name: Build VSIX

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      # the build script calls pnpm internally
      - run: corepack enable

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package
        run: npm run pack

      - uses: actions/upload-artifact@v4
        with:
          name: amaze-browser-vsix
          path: bin/*.vsix
          if-no-files-found: error
